version: '3.7'

services:

  react-admin:
    container_name: react-admin
    image: wiezmankimchi/react-admin
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development